// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxweKCKJNv2vicbWiCDCUaVyqa18-4pA',
    appId: '1:697655278626:web:691b4cd8e4e22c2bf35e7b',
    messagingSenderId: '697655278626',
    projectId: 'testcrud160403',
    authDomain: 'testcrud160403.firebaseapp.com',
    storageBucket: 'testcrud160403.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnH8fd4lzHvT8WsHNv5jSOfIpYuSa_liM',
    appId: '1:697655278626:android:65ab68dfca4ef78ef35e7b',
    messagingSenderId: '697655278626',
    projectId: 'testcrud160403',
    storageBucket: 'testcrud160403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLvpT6z27yAKqUUL3J7qEHQ16lKlchSqs',
    appId: '1:697655278626:ios:e0793639f7cf7055f35e7b',
    messagingSenderId: '697655278626',
    projectId: 'testcrud160403',
    storageBucket: 'testcrud160403.appspot.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLvpT6z27yAKqUUL3J7qEHQ16lKlchSqs',
    appId: '1:697655278626:ios:7272f3778c1a11d2f35e7b',
    messagingSenderId: '697655278626',
    projectId: 'testcrud160403',
    storageBucket: 'testcrud160403.appspot.com',
    iosBundleId: 'com.example.firebasecrud.RunnerTests',
  );
}
